#jinja2 toml


{% extends "base.toml" %}
{% block base %}

name = "default"
description = "creates a default python project"
narrative = "A simple project setup with autopep8"

[scripts]
venv = ".venv"
pip = "requirements-dev.txt"

{% endblock %}










