name = "vscode"
description = "creates a default Tobias Project"
explonation = """
Creates an project with vscode settings

"""

folders = ["{{ project }}", "test"]

files = [
    { path = "{{project}}/__init__.py" },
    { path = "requirements-dev.txt", content = "_obj:dev" },
    { path = "README.md", content = "# {{project}}" },
    { path = "test/Test{{project | title }}.py", content = "_obj:testTemplate" },
    { path = ".vscode/settings.json", content = "_obj:settings"},
    { path = ".gitignore", content = "_obj:gitignore"}
]

[content]
dev = """
black
"""

gitignore = """
__pycache__
.vscode
.venv
"""

settings = """
{
    "python.formatting.provider": "black",
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        "./test",
        "-p",
        "test*.py"
    ],
    "python.testing.pytestEnabled": false,
    "python.testing.unittestEnabled": true
}
"""

testTemplate = """
import unittest

class Test{{project | title}}(unittest.TestCase):

    def test_first(self):
        pass

if __name__ == "__main__":
    unittest.main()
"""

[scripts]
venv = ".venv"
pip = "requirements-dev.txt"
code = true
